// src/components/Shared/Footer.vue
<script setup lang="ts">
import type { FooterContent } from '../../types/home'
import Button from './Button.vue'

defineProps<{
  content: FooterContent
}>()
</script>

<template>
  <footer class="fixed bottom-0 left-0 w-full bg-brand-dark-grey/90 backdrop-blur-md border-t border-white/10 p-4 z-50 flex items-center justify-between px-8">
    <p class="text-secondary text-sm font-medium">{{ content.text }}</p>
    <Button :button="content.button" class-name="py-2 px-4 text-sm" />
  </footer>
</template>

// components/Shared/Footer.tsx
import React from 'react';
import { FooterContent } from '../../types/Home';
import Button from './Button';

interface Props {
  content: FooterContent;
}

const Footer: React.FC<Props> = ({ content }) => {
  return (
    <footer className="h-16 bg-brand-dark-grey/90 backdrop-blur-md border-t border-white/10 flex items-center justify-between px-8 text-white z-40">
      <p className="text-sm font-medium opacity-80">{content.text}</p>
      <Button button={content.button} className="py-2 px-4 text-xs" />
    </footer>
  );
};

export default Footer;
