// src/components/Shared/Modal.vue
<script setup lang="ts">
const props = defineProps<{
  isOpen: boolean
}>()

defineEmits(['close'])
</script>

<template>
  <Transition
    enter-active-class="transition duration-300 ease-out"
    enter-from-class="opacity-0"
    enter-to-class="opacity-100"
    leave-active-class="transition duration-200 ease-in"
    leave-from-class="opacity-100"
    leave-to-class="opacity-0"
  >
    <div
      v-if="isOpen"
      role="dialog"
      aria-modal="true"
      class="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/40 backdrop-blur-sm"
      @click.self="$emit('close')"
    >
      <Transition
        enter-active-class="transition duration-300 ease-out"
        enter-from-class="scale-95 opacity-0 translate-y-8"
        enter-to-class="scale-100 opacity-100 translate-y-0"
      >
        <div class="bg-brand-dark-grey/80 backdrop-blur-md border border-white/10 w-full max-w-5xl rounded-2xl shadow-2xl overflow-hidden relative">
          <!-- Close Button -->
          <button
            @click="$emit('close')"
            class="absolute top-4 right-4 text-secondary hover:text-white transition-colors z-10 p-2"
          >
            <svg class="w-6 h-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
            </svg>
          </button>

          <div class="h-full max-h-[90vh] overflow-y-auto custom-scrollbar">
            <slot />
          </div>
        </div>
      </Transition>
    </div>
  </Transition>
</template>

// components/Shared/Modal.tsx

import React, { useEffect, useState } from 'react';
import { createPortal } from 'react-dom';
import { IconClose } from './Icons';

interface ModalProps {
  isOpen: boolean;
  onClose: () => void;
  title: string;
  children: React.ReactNode;
}

const Modal: React.FC<ModalProps> = ({ isOpen, onClose, title, children }) => {
  const [isVisible, setIsVisible] = useState(false);
  const [shouldRender, setShouldRender] = useState(false);

  useEffect(() => {
    if (isOpen) {
      setShouldRender(true);
      // Small timeout to allow render before adding opacity class for transition
      setTimeout(() => setIsVisible(true), 10);
    } else {
      setIsVisible(false);
      const timer = setTimeout(() => setShouldRender(false), 300); // Match transition duration
      return () => clearTimeout(timer);
    }
  }, [isOpen]);

  if (!shouldRender) return null;

  return createPortal(
    <div className={`fixed inset-0 z-50 flex items-center justify-center p-4 sm:p-8 transition-opacity duration-300 ${isVisible ? 'opacity-100' : 'opacity-0'}`}>
      {/* Backdrop */}
      <div 
        className="absolute inset-0 bg-brand-dark-grey/80 backdrop-blur-sm" 
        onClick={onClose}
      />
      
      {/* Content Container */}
      <div 
        className={`
          relative bg-surface border border-secondary/20 w-full max-w-5xl max-h-[90vh] 
          rounded-2xl shadow-2xl overflow-hidden flex flex-col
          transform transition-all duration-300 
          ${isVisible ? 'scale-100 translate-y-0' : 'scale-95 translate-y-8'}
        `}
      >
        {/* Header */}
        <div className="flex items-center justify-between px-6 py-4 border-b border-secondary/10 bg-surface z-10">
          <h2 className="text-2xl font-bold text-white tracking-wide">{title}</h2>
          <button 
            onClick={onClose}
            className="p-2 hover:bg-secondary/10 rounded-full transition-colors text-secondary hover:text-white"
            aria-label="Close modal"
          >
            <IconClose className="w-6 h-6" />
          </button>
        </div>

        {/* Body */}
        <div className="flex-1 overflow-y-auto p-6 custom-scrollbar bg-background">
          {children}
        </div>
      </div>
    </div>,
    document.body
  );
};

export default Modal;
