// components/InteractiveMap/MapContainer.tsx

import React, { useRef, useState, useEffect, useCallback } from 'react';
import { HotspotData, MapState } from '../../types/MapTypes';
import HotspotMarker from './HotspotMarker';

interface Props {
  imageUrl: string;
  hotspots: HotspotData[];
  onHotspotClick: (data: HotspotData) => void;
  fillSpace?: boolean; // New prop: true = cover (no black bars), false = contain (show whole image)
}

// Absolute max scale (e.g. 3x original resolution)
const ABSOLUTE_MAX_SCALE = 3;
const SCROLL_SENSITIVITY = 0.001;

// Pure helper function to calculate clamped translation based on dimensions
const calculateClampedTranslation = (
  x: number,
  y: number,
  scale: number,
  imgW: number,
  imgH: number,
  contW: number,
  contH: number
) => {
    const scaledWidth = imgW * scale;
    const scaledHeight = imgH * scale;

    let targetX = x;
    let targetY = y;

    // Horizontal Clamping / Centering
    if (scaledWidth <= contW) {
        // Image fits horizontally, lock to center
        targetX = (contW - scaledWidth) / 2;
    } else {
        // Image larger than viewport, clamp to edges
        // minX is negative (panned far left), maxX is 0 (aligned left)
        const minX = contW - scaledWidth;
        const maxX = 0;
        targetX = Math.min(Math.max(x, minX), maxX);
    }

    // Vertical Clamping / Centering
    if (scaledHeight <= contH) {
        // Image fits vertically, lock to center
        targetY = (contH - scaledHeight) / 2;
    } else {
        const minY = contH - scaledHeight;
        const maxY = 0;
        targetY = Math.min(Math.max(y, minY), maxY);
    }

    return { x: targetX, y: targetY };
};

const MapContainer: React.FC<Props> = ({ imageUrl, hotspots, onHotspotClick, fillSpace = true }) => {
  const containerRef = useRef<HTMLDivElement>(null);
  const contentRef = useRef<HTMLDivElement>(null); // Wraps image + hotspots
  
  const [state, setState] = useState<MapState>({
    scale: 1,
    translation: { x: 0, y: 0 }
  });
  
  const [isDragging, setIsDragging] = useState(false);
  const [lastMousePosition, setLastMousePosition] = useState({ x: 0, y: 0 });
  const [imageDimensions, setImageDimensions] = useState({ width: 0, height: 0 });
  const [containerDimensions, setContainerDimensions] = useState({ width: 0, height: 0 });
  const [minScale, setMinScale] = useState(0.1); 

  // Helper to determine min scale based on fillSpace preference
  const calculateMinScale = useCallback((imgW: number, imgH: number, contW: number, contH: number) => {
      const scaleX = contW / imgW;
      const scaleY = contH / imgH;
      // If fillSpace is true, we take the larger scale to ensure coverage (crop excess).
      // If fillSpace is false, we take the smaller scale to ensure containment (show all).
      return fillSpace ? Math.max(scaleX, scaleY) : Math.min(scaleX, scaleY);
  }, [fillSpace]);

  // Handle Resize: Recalculate dimensions, minScale, and clamp current state
  useEffect(() => {
    const handleResize = () => {
      if (!containerRef.current) return;
      const { width, height } = containerRef.current.getBoundingClientRect();
      
      setContainerDimensions({ width, height });

      if (imageDimensions.width > 0 && imageDimensions.height > 0) {
           const newMin = calculateMinScale(imageDimensions.width, imageDimensions.height, width, height);
           
           setMinScale(newMin);

           // Adjust current state to fit new boundaries
           setState(prev => {
             // Ensure we don't zoom out further than the new minimum
             const nextScale = Math.max(prev.scale, newMin);

             const clamped = calculateClampedTranslation(
               prev.translation.x,
               prev.translation.y,
               nextScale,
               imageDimensions.width,
               imageDimensions.height,
               width,
               height
             );

             return {
               scale: nextScale,
               translation: clamped
             };
           });
      }
    };
    
    window.addEventListener('resize', handleResize);
    // Initial call to set up if image is already loaded (though onLoad handles main init)
    if (imageDimensions.width > 0) handleResize();
    
    return () => window.removeEventListener('resize', handleResize);
  }, [imageDimensions, calculateMinScale]);

  const handleImageLoad = (e: React.SyntheticEvent<HTMLImageElement>) => {
    const { naturalWidth, naturalHeight } = e.currentTarget;
    setImageDimensions({ width: naturalWidth, height: naturalHeight });
    
    if (containerRef.current) {
        const rect = containerRef.current.getBoundingClientRect();
        
        const calculatedMinScale = calculateMinScale(naturalWidth, naturalHeight, rect.width, rect.height);
        setMinScale(calculatedMinScale);
        
        // Initial Center
        const scaledW = naturalWidth * calculatedMinScale;
        const scaledH = naturalHeight * calculatedMinScale;
        const tx = (rect.width - scaledW) / 2;
        const ty = (rect.height - scaledH) / 2;

        setState({
            scale: calculatedMinScale,
            translation: { x: tx, y: ty }
        });
    }
  };

  const handleWheel = (e: React.WheelEvent) => {
    e.preventDefault();
    if (!containerRef.current) return;

    const rect = containerRef.current.getBoundingClientRect();
    const mouseX = e.clientX - rect.left;
    const mouseY = e.clientY - rect.top;

    // Calculate zoom delta
    const zoomDelta = -e.deltaY * SCROLL_SENSITIVITY;
    
    // We want to allow zooming in significantly, so ensure max scale is at least somewhat larger than minScale
    const effectiveMaxScale = Math.max(ABSOLUTE_MAX_SCALE, minScale * 3);

    let newScale = state.scale * (1 + zoomDelta);
    
    // Clamp scale between dynamic minScale and effectiveMaxScale
    newScale = Math.min(Math.max(newScale, minScale), effectiveMaxScale);
    
    if (newScale === state.scale) return;

    // Zoom towards pointer logic
    const relativeX = (mouseX - state.translation.x) / state.scale;
    const relativeY = (mouseY - state.translation.y) / state.scale;
    
    const newTx = mouseX - (relativeX * newScale);
    const newTy = mouseY - (relativeY * newScale);
    
    const clamped = calculateClampedTranslation(
        newTx, 
        newTy, 
        newScale, 
        imageDimensions.width, 
        imageDimensions.height, 
        containerDimensions.width, 
        containerDimensions.height
    );

    setState({
      scale: newScale,
      translation: clamped
    });
  };

  const handleMouseDown = (e: React.MouseEvent) => {
    setIsDragging(true);
    setLastMousePosition({ x: e.clientX, y: e.clientY });
  };

  const handleMouseMove = (e: React.MouseEvent) => {
    if (!isDragging) return;

    const dx = e.clientX - lastMousePosition.x;
    const dy = e.clientY - lastMousePosition.y;

    const newTx = state.translation.x + dx;
    const newTy = state.translation.y + dy;

    const clamped = calculateClampedTranslation(
        newTx, 
        newTy, 
        state.scale, 
        imageDimensions.width, 
        imageDimensions.height, 
        containerDimensions.width, 
        containerDimensions.height
    );

    setState(prev => ({
      ...prev,
      translation: clamped
    }));

    setLastMousePosition({ x: e.clientX, y: e.clientY });
  };

  const handleMouseUp = () => {
    setIsDragging(false);
  };

  return (
    <div 
      ref={containerRef}
      className="relative w-full h-full overflow-hidden bg-brand-black cursor-grab active:cursor-grabbing select-none"
      onWheel={handleWheel}
      onMouseDown={handleMouseDown}
      onMouseMove={handleMouseMove}
      onMouseUp={handleMouseUp}
      onMouseLeave={handleMouseUp}
    >
      {/* Transformed Content */}
      <div 
        ref={contentRef}
        style={{
          transform: `translate(${state.translation.x}px, ${state.translation.y}px) scale(${state.scale})`,
          transformOrigin: '0 0',
          width: imageDimensions.width || '100%',
          height: imageDimensions.height || '100%',
          willChange: 'transform',
        }}
        className="relative transition-transform duration-75 ease-out"
      >
        <img 
          src={imageUrl} 
          alt="Map Background" 
          className="w-full h-full object-cover pointer-events-none select-none"
          draggable={false}
          onLoad={handleImageLoad}
        />
        
        {/* Render Hotspots */}
        {imageDimensions.width > 0 && hotspots.map(hp => (
            <HotspotMarker 
                key={hp.id} 
                hotspot={hp} 
                scale={state.scale}
                onClick={onHotspotClick}
            />
        ))}
      </div>
    </div>
  );
};

export default MapContainer;

// src/components/InteractiveMap/MapContainer.vue
<script setup lang="ts">
import { ref, onMounted, onUnmounted, nextTick } from 'vue'
import type { Hotspot } from '../../types/MapTypes'
import mapDataJson from '../../data/mapData.json'
import HotspotMarker from './HotspotMarker.vue'
import Modal from '../Shared/Modal.vue'
import ContentRenderer from '../Shared/ContentRenderer.vue'
import isometric from '../../assets/isometric.png'

const mapData = mapDataJson.hotspots as Hotspot[]

const containerRef = ref<HTMLDivElement | null>(null)
const imageRef = ref<HTMLImageElement | null>(null)
const scale = ref(0.8)
const position = ref({ x: 0, y: 0 })
const isDragging = ref(false)
const dragStart = ref({ x: 0, y: 0 })
const selectedHotspot = ref<Hotspot | null>(null)

// Natural image dimensions
const IMAGE_WIDTH = 1600
const IMAGE_HEIGHT = 900

const minScale = ref(0.4)
const maxScale = 2.5

const calculateDynamicBoundaries = () => {
  if (!containerRef.value) return

  const containerRect = containerRef.value.getBoundingClientRect()

  // Calculate minimum scale to ensure image always fills container
  const scaleX = containerRect.width / IMAGE_WIDTH
  const scaleY = containerRect.height / IMAGE_HEIGHT
  minScale.value = Math.max(scaleX, scaleY)

  // Ensure current scale is not below minScale
  if (scale.value < minScale.value) {
    scale.value = minScale.value
  }

  // Re-clamp position
  position.value = calculateClampedTranslation(position.value.x, position.value.y, scale.value)
}

const handleWheel = (e: WheelEvent) => {
  e.preventDefault()
  const zoomSpeed = 0.001
  const delta = -e.deltaY
  const newScale = Math.min(Math.max(scale.value + delta * zoomSpeed, minScale.value), maxScale)

  // Re-clamp position with new scale
  position.value = calculateClampedTranslation(position.value.x, position.value.y, newScale)
  scale.value = newScale
}

const handleMouseDown = (e: MouseEvent) => {
  if (selectedHotspot.value) return
  isDragging.value = true
  dragStart.value = {
    x: e.clientX - position.value.x,
    y: e.clientY - position.value.y
  }
}

const calculateClampedTranslation = (
  x: number,
  y: number,
  currentScale: number
) => {
  if (!containerRef.value) return { x, y }

  const containerRect = containerRef.value.getBoundingClientRect()
  const scaledWidth = IMAGE_WIDTH * currentScale
  const scaledHeight = IMAGE_HEIGHT * currentScale

  // Horizontal clamping
  let clampedX = x
  if (scaledWidth <= containerRect.width) {
    clampedX = (containerRect.width - scaledWidth) / 2
  } else {
    clampedX = Math.min(0, Math.max(containerRect.width - scaledWidth, x))
  }

  // Vertical clamping
  let clampedY = y
  if (scaledHeight <= containerRect.height) {
    clampedY = (containerRect.height - scaledHeight) / 2
  } else {
    clampedY = Math.min(0, Math.max(containerRect.height - scaledHeight, y))
  }

  return { x: clampedX, y: clampedY }
}

const handleMouseMove = (e: MouseEvent) => {
  if (!isDragging.value) return

  const newX = e.clientX - dragStart.value.x
  const newY = e.clientY - dragStart.value.y

  position.value = calculateClampedTranslation(newX, newY, scale.value)
}

const handleMouseUp = () => {
  isDragging.value = false
}

const openHotspot = (hotspot: Hotspot) => {
  selectedHotspot.value = hotspot
}

const handleKeyDown = (e: KeyboardEvent) => {
  if (e.key === 'Escape' && selectedHotspot.value) {
    selectedHotspot.value = null
  }
}

let resizeObserver: ResizeObserver | null = null

onMounted(() => {
  window.addEventListener('mousemove', handleMouseMove)
  window.addEventListener('mouseup', handleMouseUp)
  window.addEventListener('keydown', handleKeyDown)

  if (containerRef.value) {
    resizeObserver = new ResizeObserver(() => {
      calculateDynamicBoundaries()
    })
    resizeObserver.observe(containerRef.value)
  }

  // Initial calculation
  nextTick(() => {
    calculateDynamicBoundaries()
    // Center map
    position.value = calculateClampedTranslation(0, 0, scale.value)
  })
})

onUnmounted(() => {
  window.removeEventListener('mousemove', handleMouseMove)
  window.removeEventListener('mouseup', handleMouseUp)
  window.removeEventListener('keydown', handleKeyDown)
  if (resizeObserver) {
    resizeObserver.disconnect()
  }
})
</script>

<template>
  <div
    ref="containerRef"
    class="relative w-full h-full overflow-hidden bg-brand-light-grey cursor-grab active:cursor-grabbing select-none"
    @wheel="handleWheel"
    @mousedown="handleMouseDown"
  >
    <div
      class="relative transition-transform duration-75 ease-out"
      :style="{
        transform: `translate(${position.x}px, ${position.y}px) scale(${scale})`,
        transformOrigin: '0 0',
        width: `${IMAGE_WIDTH}px`,
        height: `${IMAGE_HEIGHT}px`,
        willChange: 'transform'
      }"
    >
      <img
        ref="imageRef"
        :src=isometric
        alt="Map Background"
        class="w-full h-full object-cover pointer-events-none select-none"
        draggable="false"
        @load="calculateDynamicBoundaries"
      />

      <HotspotMarker
        v-for="hotspot in mapData"
        :key="hotspot.id"
        :hotspot="hotspot"
        :scale="scale"
        @click="openHotspot(hotspot)"
      />
    </div>

    <Modal
      v-if="selectedHotspot"
      :is-open="!!selectedHotspot"
      @close="selectedHotspot = null"
    >
      <ContentRenderer :content="selectedHotspot.content" />
    </Modal>
  </div>
</template>
